apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: bumxdp7yg-nodejs 
  janus-idp.io/tekton: bumxdp7yg-nodejs
  backstage.io/kubernetes-id: bumxdp7yg-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: bumxdp7yg-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml