apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: bumxdp7yg-nodejs-gitops
  description: This is GitOps manifest for bumxdp7yg-nodejs   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=bumxdp7yg-nodejs
    backstage.io/kubernetes-id: bumxdp7yg-nodejs 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: bumxdp7yg-nodejs
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:bumxdp7yg-nodejs
